// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SchedulerConfig.proto

package com.ivollo.scheduler.config;

public final class ConfigProto {
  private ConfigProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface configOrBuilder extends
      // @@protoc_insertion_point(interface_extends:scheduler.config)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string opreation = 1;</code>
     */
    boolean hasOpreation();
    /**
     * <code>required string opreation = 1;</code>
     */
    String getOpreation();
    /**
     * <code>required string opreation = 1;</code>
     */
    com.google.protobuf.ByteString
        getOpreationBytes();

    /**
     * <code>required string jobName = 2;</code>
     */
    boolean hasJobName();
    /**
     * <code>required string jobName = 2;</code>
     */
    String getJobName();
    /**
     * <code>required string jobName = 2;</code>
     */
    com.google.protobuf.ByteString
        getJobNameBytes();

    /**
     * <code>required string beanName = 3;</code>
     */
    boolean hasBeanName();
    /**
     * <code>required string beanName = 3;</code>
     */
    String getBeanName();
    /**
     * <code>required string beanName = 3;</code>
     */
    com.google.protobuf.ByteString
        getBeanNameBytes();

    /**
     * <code>required string cron = 4;</code>
     */
    boolean hasCron();
    /**
     * <code>required string cron = 4;</code>
     */
    String getCron();
    /**
     * <code>required string cron = 4;</code>
     */
    com.google.protobuf.ByteString
        getCronBytes();
  }
  /**
   * Protobuf type {@code scheduler.config}
   */
  public  static final class config extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:scheduler.config)
      configOrBuilder {
    // Use config.newBuilder() to construct.
    private config(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private config() {
      opreation_ = "";
      jobName_ = "";
      beanName_ = "";
      cron_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private config(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              opreation_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              jobName_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              beanName_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              cron_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ConfigProto.internal_static_scheduler_config_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ConfigProto.internal_static_scheduler_config_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              config.class, Builder.class);
    }

    private int bitField0_;
    public static final int OPREATION_FIELD_NUMBER = 1;
    private volatile Object opreation_;
    /**
     * <code>required string opreation = 1;</code>
     */
    public boolean hasOpreation() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string opreation = 1;</code>
     */
    public String getOpreation() {
      Object ref = opreation_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          opreation_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string opreation = 1;</code>
     */
    public com.google.protobuf.ByteString
        getOpreationBytes() {
      Object ref = opreation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        opreation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int JOBNAME_FIELD_NUMBER = 2;
    private volatile Object jobName_;
    /**
     * <code>required string jobName = 2;</code>
     */
    public boolean hasJobName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string jobName = 2;</code>
     */
    public String getJobName() {
      Object ref = jobName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          jobName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string jobName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getJobNameBytes() {
      Object ref = jobName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        jobName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BEANNAME_FIELD_NUMBER = 3;
    private volatile Object beanName_;
    /**
     * <code>required string beanName = 3;</code>
     */
    public boolean hasBeanName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string beanName = 3;</code>
     */
    public String getBeanName() {
      Object ref = beanName_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          beanName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string beanName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBeanNameBytes() {
      Object ref = beanName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        beanName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CRON_FIELD_NUMBER = 4;
    private volatile Object cron_;
    /**
     * <code>required string cron = 4;</code>
     */
    public boolean hasCron() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string cron = 4;</code>
     */
    public String getCron() {
      Object ref = cron_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          cron_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string cron = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCronBytes() {
      Object ref = cron_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cron_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasOpreation()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasJobName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBeanName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasCron()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, opreation_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, jobName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, beanName_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, cron_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, opreation_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, jobName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, beanName_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, cron_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static config parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static config parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static config parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static config parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static config parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static config parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static config parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static config parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static config parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static config parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(config prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code scheduler.config}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:scheduler.config)
        configOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ConfigProto.internal_static_scheduler_config_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ConfigProto.internal_static_scheduler_config_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                config.class, Builder.class);
      }

      // Construct using com.ivollo.scheduler.config.ConfigProto.config.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        opreation_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        jobName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        beanName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        cron_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ConfigProto.internal_static_scheduler_config_descriptor;
      }

      public config getDefaultInstanceForType() {
        return config.getDefaultInstance();
      }

      public config build() {
        config result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public config buildPartial() {
        config result = new config(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.opreation_ = opreation_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.jobName_ = jobName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.beanName_ = beanName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.cron_ = cron_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof config) {
          return mergeFrom((config)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(config other) {
        if (other == config.getDefaultInstance()) return this;
        if (other.hasOpreation()) {
          bitField0_ |= 0x00000001;
          opreation_ = other.opreation_;
          onChanged();
        }
        if (other.hasJobName()) {
          bitField0_ |= 0x00000002;
          jobName_ = other.jobName_;
          onChanged();
        }
        if (other.hasBeanName()) {
          bitField0_ |= 0x00000004;
          beanName_ = other.beanName_;
          onChanged();
        }
        if (other.hasCron()) {
          bitField0_ |= 0x00000008;
          cron_ = other.cron_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasOpreation()) {
          return false;
        }
        if (!hasJobName()) {
          return false;
        }
        if (!hasBeanName()) {
          return false;
        }
        if (!hasCron()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        config parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (config) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object opreation_ = "";
      /**
       * <code>required string opreation = 1;</code>
       */
      public boolean hasOpreation() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string opreation = 1;</code>
       */
      public String getOpreation() {
        Object ref = opreation_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            opreation_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string opreation = 1;</code>
       */
      public com.google.protobuf.ByteString
          getOpreationBytes() {
        Object ref = opreation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          opreation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string opreation = 1;</code>
       */
      public Builder setOpreation(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        opreation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string opreation = 1;</code>
       */
      public Builder clearOpreation() {
        bitField0_ = (bitField0_ & ~0x00000001);
        opreation_ = getDefaultInstance().getOpreation();
        onChanged();
        return this;
      }
      /**
       * <code>required string opreation = 1;</code>
       */
      public Builder setOpreationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        opreation_ = value;
        onChanged();
        return this;
      }

      private Object jobName_ = "";
      /**
       * <code>required string jobName = 2;</code>
       */
      public boolean hasJobName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string jobName = 2;</code>
       */
      public String getJobName() {
        Object ref = jobName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            jobName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string jobName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getJobNameBytes() {
        Object ref = jobName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          jobName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string jobName = 2;</code>
       */
      public Builder setJobName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        jobName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string jobName = 2;</code>
       */
      public Builder clearJobName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        jobName_ = getDefaultInstance().getJobName();
        onChanged();
        return this;
      }
      /**
       * <code>required string jobName = 2;</code>
       */
      public Builder setJobNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        jobName_ = value;
        onChanged();
        return this;
      }

      private Object beanName_ = "";
      /**
       * <code>required string beanName = 3;</code>
       */
      public boolean hasBeanName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string beanName = 3;</code>
       */
      public String getBeanName() {
        Object ref = beanName_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            beanName_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string beanName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getBeanNameBytes() {
        Object ref = beanName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          beanName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string beanName = 3;</code>
       */
      public Builder setBeanName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        beanName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string beanName = 3;</code>
       */
      public Builder clearBeanName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        beanName_ = getDefaultInstance().getBeanName();
        onChanged();
        return this;
      }
      /**
       * <code>required string beanName = 3;</code>
       */
      public Builder setBeanNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        beanName_ = value;
        onChanged();
        return this;
      }

      private Object cron_ = "";
      /**
       * <code>required string cron = 4;</code>
       */
      public boolean hasCron() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string cron = 4;</code>
       */
      public String getCron() {
        Object ref = cron_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            cron_ = s;
          }
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>required string cron = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCronBytes() {
        Object ref = cron_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          cron_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string cron = 4;</code>
       */
      public Builder setCron(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        cron_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string cron = 4;</code>
       */
      public Builder clearCron() {
        bitField0_ = (bitField0_ & ~0x00000008);
        cron_ = getDefaultInstance().getCron();
        onChanged();
        return this;
      }
      /**
       * <code>required string cron = 4;</code>
       */
      public Builder setCronBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        cron_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:scheduler.config)
    }

    // @@protoc_insertion_point(class_scope:scheduler.config)
    private static final config DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new config();
    }

    public static config getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @Deprecated public static final com.google.protobuf.Parser<config>
        PARSER = new com.google.protobuf.AbstractParser<config>() {
      public config parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new config(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<config> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<config> getParserForType() {
      return PARSER;
    }

    public config getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_scheduler_config_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_scheduler_config_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\025SchedulerConfig.proto\022\tscheduler\"L\n\006co" +
      "nfig\022\021\n\topreation\030\001 \002(\t\022\017\n\007jobName\030\002 \002(\t" +
      "\022\020\n\010beanName\030\003 \002(\t\022\014\n\004cron\030\004 \002(\tB*\n\033com." +
      "ivollo.scheduler.configB\013ConfigProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_scheduler_config_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_scheduler_config_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_scheduler_config_descriptor,
        new String[] { "Opreation", "JobName", "BeanName", "Cron", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
